### ISSUE TITLE
Enhancement: new social buttons

### ISSUE THREAD

**Issue by Sphinkie** [gicrisf/zhuia#2]
Hello
Bravo for your very nice Zola theme.
I have a request:
Can you please add the support (and icons) for these two "social buttons" ?

- **BookStack** [see on wikipedia](https://en.wikipedia.org/wiki/BookStack)
- **DokuWiki** [see on wikipedia](https://en.wikipedia.org/wiki/DokuWiki)

Thanks!

Edit: if needed, you will find attached a blue version of the dokuwiki logo (with or wiithout the colored arrows)

![BookStack icon](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/BookStack_logo.svg/120px-BookStack_logo.svg.png)

![DokuWikiicon](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Dokuwiki_logo.svg/120px-Dokuwiki_logo.svg.png)

![dokuwiki-noarrow](https://user-images.githubusercontent.com/25912285/219972716-1d1833dd-1196-423f-a0f2-beb0f75404e3.svg)

![dokuwiki](https://user-images.githubusercontent.com/25912285/219973027-4a71c753-0000-41a1-a1e8-44ab80266be3.svg)

**Comment by gicrisf** [comment]
Hello @Sphinkie, I have read your request and I think there is no problem with that, but I have no time at the moment, so I could make you wait a little

**Comment by gicrisf** [comment]
I hope the wait wasn't too long for you, but this apparently simple stuff takes time and I really had no time in the last month. So, I added the buttons you requested: I think the BookStack one fits well. I leave a screenshot below.

![immagine](https://user-images.githubusercontent.com/56557525/229092794-ab847cb8-554b-4244-aee1-00c6ee8be77b.png)


On the other hand, the DokuWiki icon was a bit tricky, because the space in the button is thought for really minimal icons, therefore is pretty small. Icons like the DokuWiki one usually give their best with more space or they look too crowded: I created a new vectorized version of the icon with some colors to make it more recognizable. I leave another screenshot below.

![immagine](https://user-images.githubusercontent.com/56557525/229092710-0cfe1308-67a0-4e62-9163-8e70d3a5b6fa.png)

You can try them by uncommenting the relative lines I just added to the config file.

**Comment by Sphinkie** [comment]
Thank you.
It works well.
